### ISSUE TITLE
Now able to deploy

### ISSUE THREAD

**Issue by rsilvers129** [dabear/NightscoutShareServer#2]
The "next" button is not unghosting. Not sure what to fill in for these fields.

<img width="553" alt="screen shot 2018-01-23 at 2 01 18 pm" src="https://user-images.githubusercontent.com/4177461/35295010-02242066-0046-11e8-9468-3b673472781e.png">

**Comment by dabear** [comment]
Are you logged into microsoft/azure with a user that has used any azure services before? When I try I get the following screen:

![image](https://user-images.githubusercontent.com/442324/35329579-b01973e6-0100-11e8-9c01-9333cd330c7b.png)

Please note that there is literally *nothing* I can do to help you with this problem, because it's not a problem with nightscoutshareserver, but rather in azure.

Can you try again?

**Comment by dabear** [comment]
You should also fork my app and use your forked version when deploying. E.g. you should create github.com/rsilvers129/NightscoutShareServer as a copy of my app _first_

**Comment by rsilvers129** [comment]
I think the problem is that I closed my account in the past because I moved to Heroku, and now it won’t let me get a new free account.
